/* Generated by Yosys 0.33 (git sha1 2584903a060) */

(* top =  1  *)
(* src = "atm.v:1.1-123.10" *)
module atm(balanceInicial, monto, pinTarjeta, digito, clk, rst, tarjetaRecibida, digitoSTB, montoSTB, tipoTrans, balanceActualizado, entregarDinero, fondosInsuficientes, pinIncorrecto, advertencia, alarmaBloqueo);
  (* src = "atm.v:37.1-52.4" *)
  wire [2:0] _0000_;
  (* src = "atm.v:37.1-52.4" *)
  wire [2:0] _0001_;
  (* src = "atm.v:37.1-52.4" *)
  wire [15:0] _0002_;
  wire _0003_;
  wire _0004_;
  wire _0005_;
  wire _0006_;
  wire _0007_;
  wire _0008_;
  wire _0009_;
  wire _0010_;
  wire _0011_;
  wire _0012_;
  wire _0013_;
  wire _0014_;
  wire _0015_;
  wire _0016_;
  wire _0017_;
  wire _0018_;
  wire _0019_;
  wire _0020_;
  wire _0021_;
  wire _0022_;
  wire _0023_;
  wire _0024_;
  wire _0025_;
  wire _0026_;
  wire _0027_;
  wire _0028_;
  wire _0029_;
  wire _0030_;
  wire _0031_;
  wire _0032_;
  wire _0033_;
  wire _0034_;
  wire _0035_;
  wire _0036_;
  wire _0037_;
  wire _0038_;
  wire _0039_;
  wire _0040_;
  wire _0041_;
  wire _0042_;
  wire _0043_;
  wire _0044_;
  wire _0045_;
  wire _0046_;
  wire _0047_;
  wire _0048_;
  wire _0049_;
  wire _0050_;
  wire _0051_;
  wire _0052_;
  wire _0053_;
  wire _0054_;
  wire _0055_;
  wire _0056_;
  wire _0057_;
  wire _0058_;
  wire _0059_;
  wire _0060_;
  wire _0061_;
  wire _0062_;
  wire _0063_;
  wire _0064_;
  wire _0065_;
  wire _0066_;
  wire _0067_;
  wire _0068_;
  wire _0069_;
  wire _0070_;
  wire _0071_;
  wire _0072_;
  wire _0073_;
  wire _0074_;
  wire _0075_;
  wire _0076_;
  wire _0077_;
  wire _0078_;
  wire _0079_;
  wire _0080_;
  wire _0081_;
  wire _0082_;
  wire _0083_;
  wire _0084_;
  wire _0085_;
  wire _0086_;
  wire _0087_;
  wire _0088_;
  wire _0089_;
  wire _0090_;
  wire _0091_;
  wire _0092_;
  wire _0093_;
  wire _0094_;
  wire _0095_;
  wire _0096_;
  wire _0097_;
  wire _0098_;
  wire _0099_;
  wire _0100_;
  wire _0101_;
  wire _0102_;
  wire _0103_;
  wire _0104_;
  wire _0105_;
  wire _0106_;
  wire _0107_;
  wire _0108_;
  wire _0109_;
  wire _0110_;
  wire _0111_;
  wire _0112_;
  wire _0113_;
  wire _0114_;
  wire _0115_;
  wire _0116_;
  wire _0117_;
  wire _0118_;
  wire _0119_;
  wire _0120_;
  wire _0121_;
  wire _0122_;
  wire _0123_;
  wire _0124_;
  wire _0125_;
  wire _0126_;
  wire _0127_;
  wire _0128_;
  wire _0129_;
  wire _0130_;
  wire _0131_;
  wire _0132_;
  wire _0133_;
  wire _0134_;
  wire _0135_;
  wire _0136_;
  wire _0137_;
  wire _0138_;
  wire _0139_;
  wire _0140_;
  wire _0141_;
  wire _0142_;
  wire _0143_;
  wire _0144_;
  wire _0145_;
  wire _0146_;
  wire _0147_;
  wire _0148_;
  wire _0149_;
  wire _0150_;
  wire _0151_;
  wire _0152_;
  wire _0153_;
  wire _0154_;
  wire _0155_;
  wire _0156_;
  wire _0157_;
  wire _0158_;
  wire _0159_;
  wire _0160_;
  wire _0161_;
  wire _0162_;
  wire _0163_;
  wire _0164_;
  wire _0165_;
  wire _0166_;
  wire _0167_;
  wire _0168_;
  wire _0169_;
  wire _0170_;
  wire _0171_;
  wire _0172_;
  wire _0173_;
  wire _0174_;
  wire _0175_;
  wire _0176_;
  wire _0177_;
  wire _0178_;
  wire _0179_;
  wire _0180_;
  wire _0181_;
  wire _0182_;
  wire _0183_;
  wire _0184_;
  wire _0185_;
  wire _0186_;
  wire _0187_;
  wire _0188_;
  wire _0189_;
  wire _0190_;
  wire _0191_;
  wire _0192_;
  wire _0193_;
  wire _0194_;
  wire _0195_;
  wire _0196_;
  wire _0197_;
  wire _0198_;
  wire _0199_;
  wire _0200_;
  wire _0201_;
  wire _0202_;
  wire _0203_;
  wire _0204_;
  wire _0205_;
  wire _0206_;
  wire _0207_;
  wire _0208_;
  wire _0209_;
  wire _0210_;
  wire _0211_;
  wire _0212_;
  wire _0213_;
  wire _0214_;
  wire _0215_;
  wire _0216_;
  wire _0217_;
  wire _0218_;
  wire _0219_;
  wire _0220_;
  wire _0221_;
  wire _0222_;
  wire _0223_;
  wire _0224_;
  wire _0225_;
  wire _0226_;
  wire _0227_;
  wire _0228_;
  wire _0229_;
  wire _0230_;
  wire _0231_;
  wire _0232_;
  wire _0233_;
  wire _0234_;
  wire _0235_;
  wire _0236_;
  wire _0237_;
  wire _0238_;
  wire _0239_;
  wire _0240_;
  wire _0241_;
  wire _0242_;
  wire _0243_;
  wire _0244_;
  wire _0245_;
  wire _0246_;
  wire _0247_;
  wire _0248_;
  wire _0249_;
  wire _0250_;
  wire _0251_;
  wire _0252_;
  wire _0253_;
  wire _0254_;
  wire _0255_;
  wire _0256_;
  wire _0257_;
  wire _0258_;
  wire _0259_;
  wire _0260_;
  wire _0261_;
  wire _0262_;
  wire _0263_;
  wire _0264_;
  wire _0265_;
  wire _0266_;
  wire _0267_;
  wire _0268_;
  wire _0269_;
  wire _0270_;
  wire _0271_;
  wire _0272_;
  wire _0273_;
  wire _0274_;
  wire _0275_;
  wire _0276_;
  wire _0277_;
  wire _0278_;
  wire _0279_;
  wire _0280_;
  wire _0281_;
  wire _0282_;
  wire _0283_;
  wire _0284_;
  wire _0285_;
  wire _0286_;
  wire _0287_;
  wire _0288_;
  wire _0289_;
  wire _0290_;
  wire _0291_;
  wire _0292_;
  wire _0293_;
  wire _0294_;
  wire _0295_;
  wire _0296_;
  wire _0297_;
  wire _0298_;
  wire _0299_;
  wire _0300_;
  wire _0301_;
  wire _0302_;
  wire _0303_;
  wire _0304_;
  wire _0305_;
  wire _0306_;
  wire _0307_;
  wire _0308_;
  wire _0309_;
  wire _0310_;
  wire _0311_;
  wire _0312_;
  wire _0313_;
  wire _0314_;
  wire _0315_;
  wire _0316_;
  wire _0317_;
  wire _0318_;
  wire _0319_;
  wire _0320_;
  wire _0321_;
  wire _0322_;
  wire _0323_;
  wire _0324_;
  wire _0325_;
  wire _0326_;
  wire _0327_;
  wire _0328_;
  wire _0329_;
  wire _0330_;
  wire _0331_;
  wire _0332_;
  wire _0333_;
  wire _0334_;
  wire _0335_;
  wire _0336_;
  wire _0337_;
  wire _0338_;
  wire _0339_;
  wire _0340_;
  wire _0341_;
  wire _0342_;
  wire _0343_;
  wire _0344_;
  wire _0345_;
  wire _0346_;
  wire _0347_;
  wire _0348_;
  wire _0349_;
  wire _0350_;
  wire _0351_;
  wire _0352_;
  wire _0353_;
  wire _0354_;
  wire _0355_;
  wire _0356_;
  wire _0357_;
  wire _0358_;
  wire _0359_;
  wire _0360_;
  wire _0361_;
  wire _0362_;
  wire _0363_;
  wire _0364_;
  wire _0365_;
  wire _0366_;
  wire _0367_;
  wire _0368_;
  wire _0369_;
  wire _0370_;
  wire _0371_;
  wire _0372_;
  wire _0373_;
  wire _0374_;
  wire _0375_;
  wire _0376_;
  wire _0377_;
  wire _0378_;
  wire _0379_;
  wire _0380_;
  wire _0381_;
  wire _0382_;
  wire _0383_;
  wire _0384_;
  wire _0385_;
  wire _0386_;
  wire _0387_;
  wire _0388_;
  wire _0389_;
  wire _0390_;
  wire _0391_;
  wire _0392_;
  wire _0393_;
  wire _0394_;
  wire _0395_;
  wire _0396_;
  wire _0397_;
  wire _0398_;
  wire _0399_;
  wire _0400_;
  wire _0401_;
  wire _0402_;
  wire _0403_;
  wire _0404_;
  wire _0405_;
  wire _0406_;
  wire _0407_;
  wire _0408_;
  wire _0409_;
  wire _0410_;
  wire _0411_;
  wire _0412_;
  wire _0413_;
  wire _0414_;
  wire _0415_;
  wire _0416_;
  wire _0417_;
  wire _0418_;
  wire _0419_;
  wire _0420_;
  wire _0421_;
  wire _0422_;
  wire _0423_;
  wire _0424_;
  wire _0425_;
  wire _0426_;
  wire _0427_;
  wire _0428_;
  wire _0429_;
  wire _0430_;
  wire _0431_;
  wire _0432_;
  wire _0433_;
  wire _0434_;
  wire _0435_;
  wire _0436_;
  wire _0437_;
  wire _0438_;
  wire _0439_;
  wire _0440_;
  wire _0441_;
  wire _0442_;
  wire _0443_;
  wire _0444_;
  wire _0445_;
  wire _0446_;
  wire _0447_;
  wire _0448_;
  wire _0449_;
  wire _0450_;
  wire _0451_;
  wire _0452_;
  wire _0453_;
  wire _0454_;
  wire _0455_;
  wire _0456_;
  wire _0457_;
  wire _0458_;
  wire _0459_;
  wire _0460_;
  wire _0461_;
  wire _0462_;
  wire _0463_;
  wire _0464_;
  wire _0465_;
  wire _0466_;
  wire _0467_;
  wire _0468_;
  wire _0469_;
  wire _0470_;
  wire _0471_;
  wire _0472_;
  wire _0473_;
  wire _0474_;
  wire _0475_;
  wire _0476_;
  wire _0477_;
  wire _0478_;
  wire _0479_;
  wire _0480_;
  wire _0481_;
  wire _0482_;
  wire _0483_;
  wire _0484_;
  wire _0485_;
  wire _0486_;
  wire _0487_;
  wire _0488_;
  wire _0489_;
  wire _0490_;
  wire _0491_;
  wire _0492_;
  wire _0493_;
  wire _0494_;
  wire _0495_;
  wire _0496_;
  wire _0497_;
  wire _0498_;
  wire _0499_;
  wire _0500_;
  wire _0501_;
  wire _0502_;
  wire _0503_;
  wire _0504_;
  wire _0505_;
  wire _0506_;
  wire _0507_;
  wire _0508_;
  wire _0509_;
  wire _0510_;
  wire _0511_;
  wire _0512_;
  wire _0513_;
  wire _0514_;
  wire _0515_;
  wire _0516_;
  wire _0517_;
  wire _0518_;
  wire _0519_;
  wire _0520_;
  wire _0521_;
  wire _0522_;
  wire _0523_;
  wire _0524_;
  wire _0525_;
  wire _0526_;
  wire _0527_;
  wire _0528_;
  wire _0529_;
  wire _0530_;
  wire _0531_;
  wire _0532_;
  wire _0533_;
  wire _0534_;
  wire _0535_;
  wire _0536_;
  wire _0537_;
  wire _0538_;
  wire _0539_;
  wire _0540_;
  wire _0541_;
  wire _0542_;
  wire _0543_;
  wire _0544_;
  wire _0545_;
  wire _0546_;
  wire _0547_;
  wire _0548_;
  wire _0549_;
  wire _0550_;
  wire _0551_;
  wire _0552_;
  wire _0553_;
  wire _0554_;
  wire _0555_;
  wire _0556_;
  wire _0557_;
  wire _0558_;
  wire _0559_;
  wire _0560_;
  wire _0561_;
  wire _0562_;
  wire _0563_;
  wire _0564_;
  wire _0565_;
  wire _0566_;
  wire _0567_;
  wire _0568_;
  wire _0569_;
  wire _0570_;
  wire _0571_;
  wire _0572_;
  wire _0573_;
  wire _0574_;
  wire _0575_;
  wire _0576_;
  wire _0577_;
  wire _0578_;
  wire _0579_;
  wire _0580_;
  wire _0581_;
  wire _0582_;
  wire _0583_;
  wire _0584_;
  wire _0585_;
  wire _0586_;
  wire _0587_;
  wire _0588_;
  wire _0589_;
  wire _0590_;
  wire _0591_;
  wire _0592_;
  wire _0593_;
  wire _0594_;
  wire _0595_;
  wire _0596_;
  wire _0597_;
  wire _0598_;
  wire _0599_;
  wire _0600_;
  wire _0601_;
  wire _0602_;
  wire _0603_;
  wire _0604_;
  (* src = "atm.v:17.15-17.26" *)
  output advertencia;
  wire advertencia;
  (* src = "atm.v:18.15-18.28" *)
  output alarmaBloqueo;
  wire alarmaBloqueo;
  (* src = "atm.v:13.15-13.33" *)
  output balanceActualizado;
  wire balanceActualizado;
  (* src = "atm.v:2.21-2.35" *)
  input [63:0] balanceInicial;
  wire [63:0] balanceInicial;
  (* src = "atm.v:6.15-6.18" *)
  input clk;
  wire clk;
  (* src = "atm.v:31.12-31.21" *)
  wire [2:0] cntDigito;
  (* src = "atm.v:32.12-32.24" *)
  wire [2:0] cntPinIncorr;
  (* src = "atm.v:5.20-5.26" *)
  input [3:0] digito;
  wire [3:0] digito;
  (* src = "atm.v:9.15-9.24" *)
  input digitoSTB;
  wire digitoSTB;
  (* src = "atm.v:14.15-14.29" *)
  output entregarDinero;
  wire entregarDinero;
  (* src = "atm.v:15.15-15.34" *)
  output fondosInsuficientes;
  wire fondosInsuficientes;
  (* src = "atm.v:3.21-3.26" *)
  input [31:0] monto;
  wire [31:0] monto;
  (* src = "atm.v:10.15-10.23" *)
  input montoSTB;
  wire montoSTB;
  (* src = "atm.v:16.15-16.28" *)
  output pinIncorrecto;
  wire pinIncorrecto;
  (* src = "atm.v:34.12-34.24" *)
  wire [15:0] pinIngresado;
  (* src = "atm.v:4.21-4.31" *)
  input [15:0] pinTarjeta;
  wire [15:0] pinTarjeta;
  (* src = "atm.v:7.15-7.18" *)
  input rst;
  wire rst;
  (* onehot = 32'd1 *)
  wire [5:0] state;
  (* src = "atm.v:8.15-8.30" *)
  input tarjetaRecibida;
  wire tarjetaRecibida;
  (* src = "atm.v:11.15-11.24" *)
  input tipoTrans;
  wire tipoTrans;
  NOT _0605_ (
    .A(balanceInicial[31]),
    .Y(_0009_)
  );
  NOT _0606_ (
    .A(balanceInicial[30]),
    .Y(_0010_)
  );
  NOT _0607_ (
    .A(balanceInicial[29]),
    .Y(_0011_)
  );
  NOT _0608_ (
    .A(balanceInicial[28]),
    .Y(_0012_)
  );
  NOT _0609_ (
    .A(balanceInicial[27]),
    .Y(_0013_)
  );
  NOT _0610_ (
    .A(balanceInicial[26]),
    .Y(_0014_)
  );
  NOT _0611_ (
    .A(balanceInicial[25]),
    .Y(_0015_)
  );
  NOT _0612_ (
    .A(balanceInicial[24]),
    .Y(_0016_)
  );
  NOT _0613_ (
    .A(balanceInicial[23]),
    .Y(_0017_)
  );
  NOT _0614_ (
    .A(balanceInicial[22]),
    .Y(_0018_)
  );
  NOT _0615_ (
    .A(balanceInicial[21]),
    .Y(_0019_)
  );
  NOT _0616_ (
    .A(balanceInicial[20]),
    .Y(_0020_)
  );
  NOT _0617_ (
    .A(balanceInicial[19]),
    .Y(_0021_)
  );
  NOT _0618_ (
    .A(balanceInicial[18]),
    .Y(_0022_)
  );
  NOT _0619_ (
    .A(balanceInicial[17]),
    .Y(_0023_)
  );
  NOT _0620_ (
    .A(balanceInicial[15]),
    .Y(_0024_)
  );
  NOT _0621_ (
    .A(balanceInicial[14]),
    .Y(_0025_)
  );
  NOT _0622_ (
    .A(balanceInicial[13]),
    .Y(_0026_)
  );
  NOT _0623_ (
    .A(balanceInicial[12]),
    .Y(_0027_)
  );
  NOT _0624_ (
    .A(balanceInicial[11]),
    .Y(_0028_)
  );
  NOT _0625_ (
    .A(balanceInicial[10]),
    .Y(_0029_)
  );
  NOT _0626_ (
    .A(balanceInicial[9]),
    .Y(_0030_)
  );
  NOT _0627_ (
    .A(balanceInicial[8]),
    .Y(_0031_)
  );
  NOT _0628_ (
    .A(balanceInicial[7]),
    .Y(_0032_)
  );
  NOT _0629_ (
    .A(balanceInicial[6]),
    .Y(_0033_)
  );
  NOT _0630_ (
    .A(balanceInicial[5]),
    .Y(_0034_)
  );
  NOT _0631_ (
    .A(balanceInicial[4]),
    .Y(_0035_)
  );
  NOT _0632_ (
    .A(balanceInicial[3]),
    .Y(_0036_)
  );
  NOT _0633_ (
    .A(balanceInicial[2]),
    .Y(_0037_)
  );
  NOT _0634_ (
    .A(balanceInicial[1]),
    .Y(_0038_)
  );
  NOT _0635_ (
    .A(balanceInicial[0]),
    .Y(_0039_)
  );
  NOT _0636_ (
    .A(monto[31]),
    .Y(_0040_)
  );
  NOT _0637_ (
    .A(monto[30]),
    .Y(_0041_)
  );
  NOT _0638_ (
    .A(monto[29]),
    .Y(_0042_)
  );
  NOT _0639_ (
    .A(monto[28]),
    .Y(_0043_)
  );
  NOT _0640_ (
    .A(monto[27]),
    .Y(_0044_)
  );
  NOT _0641_ (
    .A(monto[26]),
    .Y(_0045_)
  );
  NOT _0642_ (
    .A(monto[25]),
    .Y(_0046_)
  );
  NOT _0643_ (
    .A(monto[24]),
    .Y(_0047_)
  );
  NOT _0644_ (
    .A(monto[23]),
    .Y(_0048_)
  );
  NOT _0645_ (
    .A(monto[22]),
    .Y(_0049_)
  );
  NOT _0646_ (
    .A(monto[21]),
    .Y(_0050_)
  );
  NOT _0647_ (
    .A(monto[20]),
    .Y(_0051_)
  );
  NOT _0648_ (
    .A(monto[19]),
    .Y(_0052_)
  );
  NOT _0649_ (
    .A(monto[18]),
    .Y(_0053_)
  );
  NOT _0650_ (
    .A(monto[17]),
    .Y(_0054_)
  );
  NOT _0651_ (
    .A(monto[16]),
    .Y(_0055_)
  );
  NOT _0652_ (
    .A(monto[15]),
    .Y(_0056_)
  );
  NOT _0653_ (
    .A(monto[14]),
    .Y(_0057_)
  );
  NOT _0654_ (
    .A(monto[13]),
    .Y(_0058_)
  );
  NOT _0655_ (
    .A(monto[12]),
    .Y(_0059_)
  );
  NOT _0656_ (
    .A(monto[11]),
    .Y(_0060_)
  );
  NOT _0657_ (
    .A(monto[10]),
    .Y(_0061_)
  );
  NOT _0658_ (
    .A(monto[9]),
    .Y(_0062_)
  );
  NOT _0659_ (
    .A(monto[8]),
    .Y(_0063_)
  );
  NOT _0660_ (
    .A(monto[7]),
    .Y(_0064_)
  );
  NOT _0661_ (
    .A(monto[6]),
    .Y(_0065_)
  );
  NOT _0662_ (
    .A(monto[5]),
    .Y(_0066_)
  );
  NOT _0663_ (
    .A(monto[4]),
    .Y(_0067_)
  );
  NOT _0664_ (
    .A(monto[3]),
    .Y(_0068_)
  );
  NOT _0665_ (
    .A(monto[2]),
    .Y(_0069_)
  );
  NOT _0666_ (
    .A(monto[1]),
    .Y(_0070_)
  );
  NOT _0667_ (
    .A(pinIngresado[10]),
    .Y(_0071_)
  );
  NOT _0668_ (
    .A(pinIngresado[9]),
    .Y(_0072_)
  );
  NOT _0669_ (
    .A(pinIngresado[8]),
    .Y(_0073_)
  );
  NOT _0670_ (
    .A(pinIngresado[7]),
    .Y(_0074_)
  );
  NOT _0671_ (
    .A(pinIngresado[6]),
    .Y(_0075_)
  );
  NOT _0672_ (
    .A(pinIngresado[5]),
    .Y(_0076_)
  );
  NOT _0673_ (
    .A(pinIngresado[4]),
    .Y(_0077_)
  );
  NOT _0674_ (
    .A(pinIngresado[3]),
    .Y(_0078_)
  );
  NOT _0675_ (
    .A(pinIngresado[2]),
    .Y(_0079_)
  );
  NOT _0676_ (
    .A(pinIngresado[1]),
    .Y(_0080_)
  );
  NOT _0677_ (
    .A(pinIngresado[0]),
    .Y(_0081_)
  );
  NOT _0678_ (
    .A(digito[3]),
    .Y(_0082_)
  );
  NOT _0679_ (
    .A(digito[2]),
    .Y(_0083_)
  );
  NOT _0680_ (
    .A(digito[1]),
    .Y(_0084_)
  );
  NOT _0681_ (
    .A(digito[0]),
    .Y(_0085_)
  );
  NOT _0682_ (
    .A(cntDigito[2]),
    .Y(_0086_)
  );
  NOT _0683_ (
    .A(cntDigito[1]),
    .Y(_0087_)
  );
  NOT _0684_ (
    .A(cntDigito[0]),
    .Y(_0088_)
  );
  NOT _0685_ (
    .A(cntPinIncorr[2]),
    .Y(_0089_)
  );
  NOT _0686_ (
    .A(cntPinIncorr[1]),
    .Y(_0090_)
  );
  NOT _0687_ (
    .A(cntPinIncorr[0]),
    .Y(_0091_)
  );
  NOT _0688_ (
    .A(state[5]),
    .Y(_0092_)
  );
  NOT _0689_ (
    .A(state[1]),
    .Y(_0093_)
  );
  NOT _0690_ (
    .A(pinIngresado[14]),
    .Y(_0094_)
  );
  NOT _0691_ (
    .A(tipoTrans),
    .Y(_0095_)
  );
  NOT _0692_ (
    .A(rst),
    .Y(_0096_)
  );
  NOT _0693_ (
    .A(digitoSTB),
    .Y(_0097_)
  );
  NOT _0694_ (
    .A(tarjetaRecibida),
    .Y(_0098_)
  );
  NOT _0695_ (
    .A(pinTarjeta[14]),
    .Y(_0099_)
  );
  NOT _0696_ (
    .A(pinTarjeta[10]),
    .Y(_0100_)
  );
  NOT _0697_ (
    .A(pinTarjeta[8]),
    .Y(_0101_)
  );
  NOT _0698_ (
    .A(pinTarjeta[7]),
    .Y(_0102_)
  );
  NOT _0699_ (
    .A(pinTarjeta[5]),
    .Y(_0103_)
  );
  NOT _0700_ (
    .A(pinTarjeta[4]),
    .Y(_0104_)
  );
  NOT _0701_ (
    .A(pinTarjeta[3]),
    .Y(_0105_)
  );
  NOT _0702_ (
    .A(pinTarjeta[2]),
    .Y(_0106_)
  );
  NOT _0703_ (
    .A(pinTarjeta[1]),
    .Y(_0107_)
  );
  NOT _0704_ (
    .A(montoSTB),
    .Y(_0108_)
  );
  NOR _0705_ (
    .A(_0092_),
    .B(_0097_),
    .Y(_0109_)
  );
  NAND _0706_ (
    .A(cntDigito[0]),
    .B(_0109_),
    .Y(_0110_)
  );
  NOR _0707_ (
    .A(state[4]),
    .B(_0110_),
    .Y(_0111_)
  );
  NOR _0708_ (
    .A(_0087_),
    .B(_0111_),
    .Y(_0112_)
  );
  NOR _0709_ (
    .A(cntDigito[1]),
    .B(_0110_),
    .Y(_0113_)
  );
  NOR _0710_ (
    .A(_0112_),
    .B(_0113_),
    .Y(_0114_)
  );
  NOR _0711_ (
    .A(_0096_),
    .B(_0114_),
    .Y(_0000_[1])
  );
  NOR _0712_ (
    .A(cntDigito[0]),
    .B(_0109_),
    .Y(_0115_)
  );
  NOT _0713_ (
    .A(_0115_),
    .Y(_0116_)
  );
  NAND _0714_ (
    .A(rst),
    .B(_0116_),
    .Y(_0117_)
  );
  NOR _0715_ (
    .A(_0111_),
    .B(_0117_),
    .Y(_0000_[0])
  );
  NOR _0716_ (
    .A(_0086_),
    .B(cntDigito[1]),
    .Y(_0118_)
  );
  NAND _0717_ (
    .A(cntDigito[2]),
    .B(_0087_),
    .Y(_0119_)
  );
  NOR _0718_ (
    .A(cntDigito[0]),
    .B(_0119_),
    .Y(_0120_)
  );
  NAND _0719_ (
    .A(_0088_),
    .B(_0118_),
    .Y(_0121_)
  );
  NOR _0720_ (
    .A(_0079_),
    .B(pinTarjeta[2]),
    .Y(_0122_)
  );
  NOR _0721_ (
    .A(pinIngresado[2]),
    .B(_0106_),
    .Y(_0123_)
  );
  NOR _0722_ (
    .A(_0122_),
    .B(_0123_),
    .Y(_0124_)
  );
  NOR _0723_ (
    .A(pinIngresado[15]),
    .B(pinTarjeta[15]),
    .Y(_0125_)
  );
  NAND _0724_ (
    .A(pinIngresado[15]),
    .B(pinTarjeta[15]),
    .Y(_0126_)
  );
  NOT _0725_ (
    .A(_0126_),
    .Y(_0127_)
  );
  NOR _0726_ (
    .A(_0125_),
    .B(_0127_),
    .Y(_0128_)
  );
  NAND _0727_ (
    .A(pinIngresado[7]),
    .B(_0102_),
    .Y(_0129_)
  );
  NAND _0728_ (
    .A(_0074_),
    .B(pinTarjeta[7]),
    .Y(_0130_)
  );
  NAND _0729_ (
    .A(_0129_),
    .B(_0130_),
    .Y(_0131_)
  );
  NAND _0730_ (
    .A(pinIngresado[14]),
    .B(_0099_),
    .Y(_0132_)
  );
  NAND _0731_ (
    .A(_0094_),
    .B(pinTarjeta[14]),
    .Y(_0133_)
  );
  NAND _0732_ (
    .A(_0132_),
    .B(_0133_),
    .Y(_0134_)
  );
  NOR _0733_ (
    .A(_0073_),
    .B(pinTarjeta[8]),
    .Y(_0135_)
  );
  NOR _0734_ (
    .A(pinIngresado[8]),
    .B(_0101_),
    .Y(_0136_)
  );
  NOR _0735_ (
    .A(_0135_),
    .B(_0136_),
    .Y(_0137_)
  );
  NOR _0736_ (
    .A(pinIngresado[11]),
    .B(pinTarjeta[11]),
    .Y(_0138_)
  );
  NOT _0737_ (
    .A(_0138_),
    .Y(_0139_)
  );
  NAND _0738_ (
    .A(pinIngresado[11]),
    .B(pinTarjeta[11]),
    .Y(_0140_)
  );
  NAND _0739_ (
    .A(_0139_),
    .B(_0140_),
    .Y(_0141_)
  );
  NOR _0740_ (
    .A(_0077_),
    .B(pinTarjeta[4]),
    .Y(_0142_)
  );
  NOR _0741_ (
    .A(pinIngresado[4]),
    .B(_0104_),
    .Y(_0143_)
  );
  NOR _0742_ (
    .A(_0142_),
    .B(_0143_),
    .Y(_0144_)
  );
  NOR _0743_ (
    .A(pinIngresado[12]),
    .B(pinTarjeta[12]),
    .Y(_0145_)
  );
  NAND _0744_ (
    .A(pinIngresado[12]),
    .B(pinTarjeta[12]),
    .Y(_0146_)
  );
  NOT _0745_ (
    .A(_0146_),
    .Y(_0147_)
  );
  NOR _0746_ (
    .A(_0145_),
    .B(_0147_),
    .Y(_0148_)
  );
  NAND _0747_ (
    .A(pinIngresado[5]),
    .B(_0103_),
    .Y(_0149_)
  );
  NAND _0748_ (
    .A(_0076_),
    .B(pinTarjeta[5]),
    .Y(_0150_)
  );
  NAND _0749_ (
    .A(_0149_),
    .B(_0150_),
    .Y(_0151_)
  );
  NAND _0750_ (
    .A(pinIngresado[10]),
    .B(_0100_),
    .Y(_0152_)
  );
  NAND _0751_ (
    .A(_0071_),
    .B(pinTarjeta[10]),
    .Y(_0153_)
  );
  NAND _0752_ (
    .A(_0152_),
    .B(_0153_),
    .Y(_0154_)
  );
  NAND _0753_ (
    .A(pinIngresado[1]),
    .B(_0107_),
    .Y(_0155_)
  );
  NAND _0754_ (
    .A(_0080_),
    .B(pinTarjeta[1]),
    .Y(_0156_)
  );
  NAND _0755_ (
    .A(_0155_),
    .B(_0156_),
    .Y(_0157_)
  );
  NOR _0756_ (
    .A(_0078_),
    .B(pinTarjeta[3]),
    .Y(_0158_)
  );
  NOR _0757_ (
    .A(pinIngresado[3]),
    .B(_0105_),
    .Y(_0159_)
  );
  NOR _0758_ (
    .A(_0158_),
    .B(_0159_),
    .Y(_0160_)
  );
  NOR _0759_ (
    .A(pinIngresado[0]),
    .B(pinTarjeta[0]),
    .Y(_0161_)
  );
  NOT _0760_ (
    .A(_0161_),
    .Y(_0162_)
  );
  NAND _0761_ (
    .A(pinIngresado[0]),
    .B(pinTarjeta[0]),
    .Y(_0163_)
  );
  NAND _0762_ (
    .A(_0162_),
    .B(_0163_),
    .Y(_0164_)
  );
  NAND _0763_ (
    .A(_0144_),
    .B(_0164_),
    .Y(_0165_)
  );
  NOR _0764_ (
    .A(pinIngresado[9]),
    .B(pinTarjeta[9]),
    .Y(_0166_)
  );
  NAND _0765_ (
    .A(pinIngresado[9]),
    .B(pinTarjeta[9]),
    .Y(_0167_)
  );
  NOT _0766_ (
    .A(_0167_),
    .Y(_0168_)
  );
  NOR _0767_ (
    .A(_0166_),
    .B(_0168_),
    .Y(_0169_)
  );
  NOR _0768_ (
    .A(pinIngresado[13]),
    .B(pinTarjeta[13]),
    .Y(_0170_)
  );
  NAND _0769_ (
    .A(pinIngresado[13]),
    .B(pinTarjeta[13]),
    .Y(_0171_)
  );
  NOT _0770_ (
    .A(_0171_),
    .Y(_0172_)
  );
  NOR _0771_ (
    .A(_0170_),
    .B(_0172_),
    .Y(_0173_)
  );
  NOR _0772_ (
    .A(_0169_),
    .B(_0173_),
    .Y(_0174_)
  );
  NOR _0773_ (
    .A(_0151_),
    .B(_0157_),
    .Y(_0175_)
  );
  NAND _0774_ (
    .A(_0124_),
    .B(_0160_),
    .Y(_0176_)
  );
  NOR _0775_ (
    .A(_0128_),
    .B(_0134_),
    .Y(_0177_)
  );
  NOR _0776_ (
    .A(pinIngresado[6]),
    .B(pinTarjeta[6]),
    .Y(_0178_)
  );
  NAND _0777_ (
    .A(pinIngresado[6]),
    .B(pinTarjeta[6]),
    .Y(_0179_)
  );
  NOT _0778_ (
    .A(_0179_),
    .Y(_0180_)
  );
  NOR _0779_ (
    .A(_0178_),
    .B(_0180_),
    .Y(_0181_)
  );
  NOR _0780_ (
    .A(_0131_),
    .B(_0181_),
    .Y(_0182_)
  );
  NOR _0781_ (
    .A(_0165_),
    .B(_0176_),
    .Y(_0183_)
  );
  NAND _0782_ (
    .A(_0175_),
    .B(_0183_),
    .Y(_0184_)
  );
  NAND _0783_ (
    .A(_0174_),
    .B(_0182_),
    .Y(_0185_)
  );
  NOR _0784_ (
    .A(_0184_),
    .B(_0185_),
    .Y(_0186_)
  );
  NOR _0785_ (
    .A(_0148_),
    .B(_0154_),
    .Y(_0187_)
  );
  NAND _0786_ (
    .A(_0137_),
    .B(_0187_),
    .Y(_0188_)
  );
  NAND _0787_ (
    .A(_0141_),
    .B(_0177_),
    .Y(_0189_)
  );
  NOR _0788_ (
    .A(_0188_),
    .B(_0189_),
    .Y(_0190_)
  );
  NAND _0789_ (
    .A(_0186_),
    .B(_0190_),
    .Y(_0191_)
  );
  NOT _0790_ (
    .A(_0191_),
    .Y(_0192_)
  );
  NOR _0791_ (
    .A(_0121_),
    .B(_0192_),
    .Y(_0193_)
  );
  NAND _0792_ (
    .A(_0120_),
    .B(_0191_),
    .Y(_0194_)
  );
  NAND _0793_ (
    .A(state[4]),
    .B(_0193_),
    .Y(_0195_)
  );
  NOT _0794_ (
    .A(_0195_),
    .Y(pinIncorrecto)
  );
  NAND _0795_ (
    .A(cntPinIncorr[1]),
    .B(_0195_),
    .Y(_0196_)
  );
  NOT _0796_ (
    .A(_0196_),
    .Y(_0197_)
  );
  NOR _0797_ (
    .A(cntPinIncorr[1]),
    .B(_0091_),
    .Y(_0198_)
  );
  NOR _0798_ (
    .A(_0090_),
    .B(cntPinIncorr[0]),
    .Y(_0199_)
  );
  NOT _0799_ (
    .A(_0199_),
    .Y(_0200_)
  );
  NOR _0800_ (
    .A(_0198_),
    .B(_0199_),
    .Y(_0201_)
  );
  NOR _0801_ (
    .A(_0195_),
    .B(_0201_),
    .Y(_0202_)
  );
  NOR _0802_ (
    .A(_0197_),
    .B(_0202_),
    .Y(_0203_)
  );
  NOR _0803_ (
    .A(_0096_),
    .B(_0203_),
    .Y(_0001_[1])
  );
  NAND _0804_ (
    .A(cntPinIncorr[0]),
    .B(_0195_),
    .Y(_0204_)
  );
  NOT _0805_ (
    .A(_0204_),
    .Y(_0205_)
  );
  NOR _0806_ (
    .A(cntPinIncorr[0]),
    .B(_0195_),
    .Y(_0206_)
  );
  NOR _0807_ (
    .A(_0205_),
    .B(_0206_),
    .Y(_0207_)
  );
  NOR _0808_ (
    .A(_0096_),
    .B(_0207_),
    .Y(_0001_[0])
  );
  NOR _0809_ (
    .A(state[4]),
    .B(state[5]),
    .Y(_0208_)
  );
  NOR _0810_ (
    .A(state[1]),
    .B(state[2]),
    .Y(_0209_)
  );
  NOT _0811_ (
    .A(_0209_),
    .Y(_0210_)
  );
  NAND _0812_ (
    .A(_0208_),
    .B(_0209_),
    .Y(_0211_)
  );
  NOR _0813_ (
    .A(_0094_),
    .B(_0211_),
    .Y(_0212_)
  );
  NAND _0814_ (
    .A(pinIngresado[10]),
    .B(_0109_),
    .Y(_0213_)
  );
  NOT _0815_ (
    .A(_0213_),
    .Y(_0214_)
  );
  NOR _0816_ (
    .A(pinIngresado[14]),
    .B(_0214_),
    .Y(_0215_)
  );
  NAND _0817_ (
    .A(state[4]),
    .B(_0194_),
    .Y(_0216_)
  );
  NOR _0818_ (
    .A(_0098_),
    .B(_0209_),
    .Y(_0217_)
  );
  NAND _0819_ (
    .A(tarjetaRecibida),
    .B(_0210_),
    .Y(_0218_)
  );
  NAND _0820_ (
    .A(_0071_),
    .B(digitoSTB),
    .Y(_0219_)
  );
  NAND _0821_ (
    .A(state[5]),
    .B(_0219_),
    .Y(_0220_)
  );
  NAND _0822_ (
    .A(_0216_),
    .B(_0220_),
    .Y(_0221_)
  );
  NOR _0823_ (
    .A(_0217_),
    .B(_0221_),
    .Y(_0222_)
  );
  NOR _0824_ (
    .A(_0215_),
    .B(_0222_),
    .Y(_0223_)
  );
  NOR _0825_ (
    .A(_0212_),
    .B(_0223_),
    .Y(_0224_)
  );
  NOR _0826_ (
    .A(_0096_),
    .B(_0224_),
    .Y(_0002_[14])
  );
  NAND _0827_ (
    .A(pinIngresado[9]),
    .B(_0109_),
    .Y(_0225_)
  );
  NAND _0828_ (
    .A(_0211_),
    .B(_0218_),
    .Y(_0226_)
  );
  NOR _0829_ (
    .A(_0092_),
    .B(digitoSTB),
    .Y(_0227_)
  );
  NAND _0830_ (
    .A(state[5]),
    .B(_0097_),
    .Y(_0228_)
  );
  NOR _0831_ (
    .A(_0226_),
    .B(_0227_),
    .Y(_0229_)
  );
  NAND _0832_ (
    .A(_0216_),
    .B(_0229_),
    .Y(_0230_)
  );
  NAND _0833_ (
    .A(pinIngresado[13]),
    .B(_0230_),
    .Y(_0231_)
  );
  NAND _0834_ (
    .A(_0225_),
    .B(_0231_),
    .Y(_0232_)
  );
  NAND _0835_ (
    .A(rst),
    .B(_0232_),
    .Y(_0233_)
  );
  NOT _0836_ (
    .A(_0233_),
    .Y(_0002_[13])
  );
  NAND _0837_ (
    .A(pinIngresado[8]),
    .B(_0109_),
    .Y(_0234_)
  );
  NAND _0838_ (
    .A(pinIngresado[12]),
    .B(_0230_),
    .Y(_0235_)
  );
  NAND _0839_ (
    .A(_0234_),
    .B(_0235_),
    .Y(_0236_)
  );
  NAND _0840_ (
    .A(rst),
    .B(_0236_),
    .Y(_0237_)
  );
  NOT _0841_ (
    .A(_0237_),
    .Y(_0002_[12])
  );
  NAND _0842_ (
    .A(pinIngresado[7]),
    .B(_0109_),
    .Y(_0238_)
  );
  NAND _0843_ (
    .A(pinIngresado[11]),
    .B(_0230_),
    .Y(_0239_)
  );
  NAND _0844_ (
    .A(_0238_),
    .B(_0239_),
    .Y(_0240_)
  );
  NAND _0845_ (
    .A(rst),
    .B(_0240_),
    .Y(_0241_)
  );
  NOT _0846_ (
    .A(_0241_),
    .Y(_0002_[11])
  );
  NAND _0847_ (
    .A(pinIngresado[10]),
    .B(_0226_),
    .Y(_0242_)
  );
  NAND _0848_ (
    .A(pinIngresado[6]),
    .B(_0109_),
    .Y(_0243_)
  );
  NAND _0849_ (
    .A(_0071_),
    .B(_0243_),
    .Y(_0244_)
  );
  NAND _0850_ (
    .A(_0075_),
    .B(digitoSTB),
    .Y(_0245_)
  );
  NAND _0851_ (
    .A(state[5]),
    .B(_0245_),
    .Y(_0246_)
  );
  NAND _0852_ (
    .A(_0216_),
    .B(_0246_),
    .Y(_0247_)
  );
  NAND _0853_ (
    .A(_0244_),
    .B(_0247_),
    .Y(_0248_)
  );
  NAND _0854_ (
    .A(_0242_),
    .B(_0248_),
    .Y(_0249_)
  );
  NAND _0855_ (
    .A(rst),
    .B(_0249_),
    .Y(_0250_)
  );
  NOT _0856_ (
    .A(_0250_),
    .Y(_0002_[10])
  );
  NAND _0857_ (
    .A(pinIngresado[9]),
    .B(_0226_),
    .Y(_0251_)
  );
  NAND _0858_ (
    .A(pinIngresado[5]),
    .B(_0109_),
    .Y(_0252_)
  );
  NAND _0859_ (
    .A(_0072_),
    .B(_0252_),
    .Y(_0253_)
  );
  NAND _0860_ (
    .A(_0076_),
    .B(digitoSTB),
    .Y(_0254_)
  );
  NAND _0861_ (
    .A(state[5]),
    .B(_0254_),
    .Y(_0255_)
  );
  NAND _0862_ (
    .A(_0216_),
    .B(_0255_),
    .Y(_0256_)
  );
  NAND _0863_ (
    .A(_0253_),
    .B(_0256_),
    .Y(_0257_)
  );
  NAND _0864_ (
    .A(_0251_),
    .B(_0257_),
    .Y(_0258_)
  );
  NAND _0865_ (
    .A(rst),
    .B(_0258_),
    .Y(_0259_)
  );
  NOT _0866_ (
    .A(_0259_),
    .Y(_0002_[9])
  );
  NAND _0867_ (
    .A(pinIngresado[8]),
    .B(_0226_),
    .Y(_0260_)
  );
  NAND _0868_ (
    .A(pinIngresado[4]),
    .B(_0109_),
    .Y(_0261_)
  );
  NAND _0869_ (
    .A(_0073_),
    .B(_0261_),
    .Y(_0262_)
  );
  NAND _0870_ (
    .A(_0077_),
    .B(digitoSTB),
    .Y(_0263_)
  );
  NAND _0871_ (
    .A(state[5]),
    .B(_0263_),
    .Y(_0264_)
  );
  NAND _0872_ (
    .A(_0216_),
    .B(_0264_),
    .Y(_0265_)
  );
  NAND _0873_ (
    .A(_0262_),
    .B(_0265_),
    .Y(_0266_)
  );
  NAND _0874_ (
    .A(_0260_),
    .B(_0266_),
    .Y(_0267_)
  );
  NAND _0875_ (
    .A(rst),
    .B(_0267_),
    .Y(_0268_)
  );
  NOT _0876_ (
    .A(_0268_),
    .Y(_0002_[8])
  );
  NAND _0877_ (
    .A(pinIngresado[7]),
    .B(_0226_),
    .Y(_0269_)
  );
  NAND _0878_ (
    .A(pinIngresado[3]),
    .B(_0109_),
    .Y(_0270_)
  );
  NAND _0879_ (
    .A(_0074_),
    .B(_0270_),
    .Y(_0271_)
  );
  NAND _0880_ (
    .A(_0078_),
    .B(digitoSTB),
    .Y(_0272_)
  );
  NAND _0881_ (
    .A(state[5]),
    .B(_0272_),
    .Y(_0273_)
  );
  NAND _0882_ (
    .A(_0216_),
    .B(_0273_),
    .Y(_0274_)
  );
  NAND _0883_ (
    .A(_0271_),
    .B(_0274_),
    .Y(_0275_)
  );
  NAND _0884_ (
    .A(_0269_),
    .B(_0275_),
    .Y(_0276_)
  );
  NAND _0885_ (
    .A(rst),
    .B(_0276_),
    .Y(_0277_)
  );
  NOT _0886_ (
    .A(_0277_),
    .Y(_0002_[7])
  );
  NAND _0887_ (
    .A(pinIngresado[6]),
    .B(_0226_),
    .Y(_0278_)
  );
  NAND _0888_ (
    .A(pinIngresado[2]),
    .B(_0109_),
    .Y(_0279_)
  );
  NAND _0889_ (
    .A(_0075_),
    .B(_0279_),
    .Y(_0280_)
  );
  NAND _0890_ (
    .A(_0079_),
    .B(digitoSTB),
    .Y(_0281_)
  );
  NAND _0891_ (
    .A(state[5]),
    .B(_0281_),
    .Y(_0282_)
  );
  NAND _0892_ (
    .A(_0216_),
    .B(_0282_),
    .Y(_0283_)
  );
  NAND _0893_ (
    .A(_0280_),
    .B(_0283_),
    .Y(_0284_)
  );
  NAND _0894_ (
    .A(_0278_),
    .B(_0284_),
    .Y(_0285_)
  );
  NAND _0895_ (
    .A(rst),
    .B(_0285_),
    .Y(_0286_)
  );
  NOT _0896_ (
    .A(_0286_),
    .Y(_0002_[6])
  );
  NAND _0897_ (
    .A(pinIngresado[5]),
    .B(_0226_),
    .Y(_0287_)
  );
  NAND _0898_ (
    .A(pinIngresado[1]),
    .B(_0109_),
    .Y(_0288_)
  );
  NAND _0899_ (
    .A(_0076_),
    .B(_0288_),
    .Y(_0289_)
  );
  NAND _0900_ (
    .A(_0080_),
    .B(digitoSTB),
    .Y(_0290_)
  );
  NAND _0901_ (
    .A(state[5]),
    .B(_0290_),
    .Y(_0291_)
  );
  NAND _0902_ (
    .A(_0216_),
    .B(_0291_),
    .Y(_0292_)
  );
  NAND _0903_ (
    .A(_0289_),
    .B(_0292_),
    .Y(_0293_)
  );
  NAND _0904_ (
    .A(_0287_),
    .B(_0293_),
    .Y(_0294_)
  );
  NAND _0905_ (
    .A(rst),
    .B(_0294_),
    .Y(_0295_)
  );
  NOT _0906_ (
    .A(_0295_),
    .Y(_0002_[5])
  );
  NAND _0907_ (
    .A(pinIngresado[4]),
    .B(_0226_),
    .Y(_0296_)
  );
  NAND _0908_ (
    .A(pinIngresado[0]),
    .B(_0109_),
    .Y(_0297_)
  );
  NAND _0909_ (
    .A(_0077_),
    .B(_0297_),
    .Y(_0298_)
  );
  NAND _0910_ (
    .A(_0081_),
    .B(digitoSTB),
    .Y(_0299_)
  );
  NAND _0911_ (
    .A(state[5]),
    .B(_0299_),
    .Y(_0300_)
  );
  NAND _0912_ (
    .A(_0216_),
    .B(_0300_),
    .Y(_0301_)
  );
  NAND _0913_ (
    .A(_0298_),
    .B(_0301_),
    .Y(_0302_)
  );
  NAND _0914_ (
    .A(_0296_),
    .B(_0302_),
    .Y(_0303_)
  );
  NAND _0915_ (
    .A(rst),
    .B(_0303_),
    .Y(_0304_)
  );
  NOT _0916_ (
    .A(_0304_),
    .Y(_0002_[4])
  );
  NAND _0917_ (
    .A(pinIngresado[3]),
    .B(_0226_),
    .Y(_0305_)
  );
  NAND _0918_ (
    .A(digito[3]),
    .B(_0109_),
    .Y(_0306_)
  );
  NAND _0919_ (
    .A(_0078_),
    .B(_0306_),
    .Y(_0307_)
  );
  NAND _0920_ (
    .A(_0082_),
    .B(digitoSTB),
    .Y(_0308_)
  );
  NAND _0921_ (
    .A(state[5]),
    .B(_0308_),
    .Y(_0309_)
  );
  NAND _0922_ (
    .A(_0216_),
    .B(_0309_),
    .Y(_0310_)
  );
  NAND _0923_ (
    .A(_0307_),
    .B(_0310_),
    .Y(_0311_)
  );
  NAND _0924_ (
    .A(_0305_),
    .B(_0311_),
    .Y(_0312_)
  );
  NAND _0925_ (
    .A(rst),
    .B(_0312_),
    .Y(_0313_)
  );
  NOT _0926_ (
    .A(_0313_),
    .Y(_0002_[3])
  );
  NAND _0927_ (
    .A(pinIngresado[2]),
    .B(_0226_),
    .Y(_0314_)
  );
  NAND _0928_ (
    .A(digito[2]),
    .B(_0109_),
    .Y(_0315_)
  );
  NAND _0929_ (
    .A(_0079_),
    .B(_0315_),
    .Y(_0316_)
  );
  NAND _0930_ (
    .A(_0083_),
    .B(digitoSTB),
    .Y(_0317_)
  );
  NAND _0931_ (
    .A(state[5]),
    .B(_0317_),
    .Y(_0318_)
  );
  NAND _0932_ (
    .A(_0216_),
    .B(_0318_),
    .Y(_0319_)
  );
  NAND _0933_ (
    .A(_0316_),
    .B(_0319_),
    .Y(_0320_)
  );
  NAND _0934_ (
    .A(_0314_),
    .B(_0320_),
    .Y(_0321_)
  );
  NAND _0935_ (
    .A(rst),
    .B(_0321_),
    .Y(_0322_)
  );
  NOT _0936_ (
    .A(_0322_),
    .Y(_0002_[2])
  );
  NAND _0937_ (
    .A(pinIngresado[1]),
    .B(_0226_),
    .Y(_0323_)
  );
  NAND _0938_ (
    .A(digito[1]),
    .B(_0109_),
    .Y(_0324_)
  );
  NAND _0939_ (
    .A(_0080_),
    .B(_0324_),
    .Y(_0325_)
  );
  NAND _0940_ (
    .A(_0084_),
    .B(digitoSTB),
    .Y(_0326_)
  );
  NAND _0941_ (
    .A(state[5]),
    .B(_0326_),
    .Y(_0327_)
  );
  NAND _0942_ (
    .A(_0216_),
    .B(_0327_),
    .Y(_0328_)
  );
  NAND _0943_ (
    .A(_0325_),
    .B(_0328_),
    .Y(_0329_)
  );
  NAND _0944_ (
    .A(_0323_),
    .B(_0329_),
    .Y(_0330_)
  );
  NAND _0945_ (
    .A(rst),
    .B(_0330_),
    .Y(_0331_)
  );
  NOT _0946_ (
    .A(_0331_),
    .Y(_0002_[1])
  );
  NAND _0947_ (
    .A(pinIngresado[0]),
    .B(_0226_),
    .Y(_0332_)
  );
  NAND _0948_ (
    .A(digito[0]),
    .B(_0109_),
    .Y(_0333_)
  );
  NAND _0949_ (
    .A(_0081_),
    .B(_0333_),
    .Y(_0334_)
  );
  NAND _0950_ (
    .A(_0085_),
    .B(digitoSTB),
    .Y(_0335_)
  );
  NAND _0951_ (
    .A(state[5]),
    .B(_0335_),
    .Y(_0336_)
  );
  NAND _0952_ (
    .A(_0216_),
    .B(_0336_),
    .Y(_0337_)
  );
  NAND _0953_ (
    .A(_0334_),
    .B(_0337_),
    .Y(_0338_)
  );
  NAND _0954_ (
    .A(_0332_),
    .B(_0338_),
    .Y(_0339_)
  );
  NAND _0955_ (
    .A(rst),
    .B(_0339_),
    .Y(_0340_)
  );
  NOT _0956_ (
    .A(_0340_),
    .Y(_0002_[0])
  );
  NOR _0957_ (
    .A(balanceInicial[7]),
    .B(_0064_),
    .Y(_0341_)
  );
  NOR _0958_ (
    .A(_0032_),
    .B(monto[7]),
    .Y(_0342_)
  );
  NOR _0959_ (
    .A(balanceInicial[6]),
    .B(_0065_),
    .Y(_0343_)
  );
  NOR _0960_ (
    .A(_0033_),
    .B(monto[6]),
    .Y(_0344_)
  );
  NOR _0961_ (
    .A(balanceInicial[5]),
    .B(_0066_),
    .Y(_0345_)
  );
  NOR _0962_ (
    .A(_0034_),
    .B(monto[5]),
    .Y(_0346_)
  );
  NOR _0963_ (
    .A(balanceInicial[4]),
    .B(_0067_),
    .Y(_0347_)
  );
  NOR _0964_ (
    .A(_0035_),
    .B(monto[4]),
    .Y(_0348_)
  );
  NOR _0965_ (
    .A(balanceInicial[3]),
    .B(_0068_),
    .Y(_0349_)
  );
  NOR _0966_ (
    .A(_0036_),
    .B(monto[3]),
    .Y(_0350_)
  );
  NOR _0967_ (
    .A(balanceInicial[2]),
    .B(_0069_),
    .Y(_0351_)
  );
  NOR _0968_ (
    .A(balanceInicial[1]),
    .B(_0070_),
    .Y(_0352_)
  );
  NOR _0969_ (
    .A(_0039_),
    .B(monto[0]),
    .Y(_0353_)
  );
  NOR _0970_ (
    .A(_0038_),
    .B(monto[1]),
    .Y(_0354_)
  );
  NOR _0971_ (
    .A(_0353_),
    .B(_0354_),
    .Y(_0355_)
  );
  NOR _0972_ (
    .A(_0352_),
    .B(_0355_),
    .Y(_0356_)
  );
  NOR _0973_ (
    .A(_0037_),
    .B(monto[2]),
    .Y(_0357_)
  );
  NOR _0974_ (
    .A(_0356_),
    .B(_0357_),
    .Y(_0358_)
  );
  NOR _0975_ (
    .A(_0351_),
    .B(_0358_),
    .Y(_0359_)
  );
  NOR _0976_ (
    .A(_0350_),
    .B(_0359_),
    .Y(_0360_)
  );
  NOR _0977_ (
    .A(_0349_),
    .B(_0360_),
    .Y(_0361_)
  );
  NOR _0978_ (
    .A(_0348_),
    .B(_0361_),
    .Y(_0362_)
  );
  NOR _0979_ (
    .A(_0347_),
    .B(_0362_),
    .Y(_0363_)
  );
  NOR _0980_ (
    .A(_0346_),
    .B(_0363_),
    .Y(_0364_)
  );
  NOR _0981_ (
    .A(_0345_),
    .B(_0364_),
    .Y(_0365_)
  );
  NOR _0982_ (
    .A(_0344_),
    .B(_0365_),
    .Y(_0366_)
  );
  NOR _0983_ (
    .A(_0343_),
    .B(_0366_),
    .Y(_0367_)
  );
  NOR _0984_ (
    .A(_0342_),
    .B(_0367_),
    .Y(_0368_)
  );
  NOR _0985_ (
    .A(_0341_),
    .B(_0368_),
    .Y(_0369_)
  );
  NAND _0986_ (
    .A(_0028_),
    .B(monto[11]),
    .Y(_0370_)
  );
  NAND _0987_ (
    .A(balanceInicial[11]),
    .B(_0060_),
    .Y(_0371_)
  );
  NAND _0988_ (
    .A(_0370_),
    .B(_0371_),
    .Y(_0372_)
  );
  NAND _0989_ (
    .A(balanceInicial[10]),
    .B(_0061_),
    .Y(_0373_)
  );
  NAND _0990_ (
    .A(_0029_),
    .B(monto[10]),
    .Y(_0374_)
  );
  NOT _0991_ (
    .A(_0374_),
    .Y(_0375_)
  );
  NAND _0992_ (
    .A(_0373_),
    .B(_0374_),
    .Y(_0376_)
  );
  NOR _0993_ (
    .A(_0372_),
    .B(_0375_),
    .Y(_0377_)
  );
  NOR _0994_ (
    .A(_0372_),
    .B(_0376_),
    .Y(_0378_)
  );
  NAND _0995_ (
    .A(_0373_),
    .B(_0377_),
    .Y(_0379_)
  );
  NOR _0996_ (
    .A(balanceInicial[9]),
    .B(_0062_),
    .Y(_0380_)
  );
  NAND _0997_ (
    .A(_0030_),
    .B(monto[9]),
    .Y(_0381_)
  );
  NAND _0998_ (
    .A(balanceInicial[9]),
    .B(_0062_),
    .Y(_0382_)
  );
  NAND _0999_ (
    .A(_0381_),
    .B(_0382_),
    .Y(_0383_)
  );
  NAND _1000_ (
    .A(_0031_),
    .B(monto[8]),
    .Y(_0384_)
  );
  NAND _1001_ (
    .A(balanceInicial[8]),
    .B(_0063_),
    .Y(_0385_)
  );
  NAND _1002_ (
    .A(_0384_),
    .B(_0385_),
    .Y(_0386_)
  );
  NOR _1003_ (
    .A(_0383_),
    .B(_0386_),
    .Y(_0387_)
  );
  NAND _1004_ (
    .A(_0378_),
    .B(_0387_),
    .Y(_0388_)
  );
  NOR _1005_ (
    .A(_0369_),
    .B(_0388_),
    .Y(_0389_)
  );
  NOR _1006_ (
    .A(_0383_),
    .B(_0384_),
    .Y(_0390_)
  );
  NOR _1007_ (
    .A(_0380_),
    .B(_0390_),
    .Y(_0391_)
  );
  NOR _1008_ (
    .A(_0379_),
    .B(_0391_),
    .Y(_0392_)
  );
  NOR _1009_ (
    .A(_0372_),
    .B(_0374_),
    .Y(_0393_)
  );
  NOR _1010_ (
    .A(_0392_),
    .B(_0393_),
    .Y(_0394_)
  );
  NAND _1011_ (
    .A(_0370_),
    .B(_0394_),
    .Y(_0395_)
  );
  NOR _1012_ (
    .A(_0389_),
    .B(_0395_),
    .Y(_0396_)
  );
  NAND _1013_ (
    .A(_0024_),
    .B(monto[15]),
    .Y(_0397_)
  );
  NAND _1014_ (
    .A(balanceInicial[15]),
    .B(_0056_),
    .Y(_0398_)
  );
  NAND _1015_ (
    .A(_0397_),
    .B(_0398_),
    .Y(_0399_)
  );
  NAND _1016_ (
    .A(balanceInicial[14]),
    .B(_0057_),
    .Y(_0400_)
  );
  NAND _1017_ (
    .A(_0025_),
    .B(monto[14]),
    .Y(_0401_)
  );
  NOT _1018_ (
    .A(_0401_),
    .Y(_0402_)
  );
  NAND _1019_ (
    .A(_0400_),
    .B(_0401_),
    .Y(_0403_)
  );
  NOR _1020_ (
    .A(_0399_),
    .B(_0402_),
    .Y(_0404_)
  );
  NOR _1021_ (
    .A(_0399_),
    .B(_0403_),
    .Y(_0405_)
  );
  NAND _1022_ (
    .A(_0400_),
    .B(_0404_),
    .Y(_0406_)
  );
  NOR _1023_ (
    .A(balanceInicial[13]),
    .B(_0058_),
    .Y(_0407_)
  );
  NAND _1024_ (
    .A(_0026_),
    .B(monto[13]),
    .Y(_0408_)
  );
  NAND _1025_ (
    .A(balanceInicial[13]),
    .B(_0058_),
    .Y(_0409_)
  );
  NAND _1026_ (
    .A(_0408_),
    .B(_0409_),
    .Y(_0410_)
  );
  NAND _1027_ (
    .A(_0027_),
    .B(monto[12]),
    .Y(_0411_)
  );
  NAND _1028_ (
    .A(balanceInicial[12]),
    .B(_0059_),
    .Y(_0412_)
  );
  NAND _1029_ (
    .A(_0411_),
    .B(_0412_),
    .Y(_0413_)
  );
  NOR _1030_ (
    .A(_0410_),
    .B(_0413_),
    .Y(_0414_)
  );
  NAND _1031_ (
    .A(_0405_),
    .B(_0414_),
    .Y(_0415_)
  );
  NOR _1032_ (
    .A(_0396_),
    .B(_0415_),
    .Y(_0416_)
  );
  NOR _1033_ (
    .A(_0410_),
    .B(_0411_),
    .Y(_0417_)
  );
  NOR _1034_ (
    .A(_0407_),
    .B(_0417_),
    .Y(_0418_)
  );
  NOR _1035_ (
    .A(_0406_),
    .B(_0418_),
    .Y(_0419_)
  );
  NOR _1036_ (
    .A(_0399_),
    .B(_0401_),
    .Y(_0420_)
  );
  NOR _1037_ (
    .A(_0419_),
    .B(_0420_),
    .Y(_0421_)
  );
  NAND _1038_ (
    .A(_0397_),
    .B(_0421_),
    .Y(_0422_)
  );
  NOR _1039_ (
    .A(_0416_),
    .B(_0422_),
    .Y(_0423_)
  );
  NAND _1040_ (
    .A(balanceInicial[24]),
    .B(_0047_),
    .Y(_0424_)
  );
  NAND _1041_ (
    .A(_0010_),
    .B(monto[30]),
    .Y(_0425_)
  );
  NAND _1042_ (
    .A(balanceInicial[30]),
    .B(_0041_),
    .Y(_0426_)
  );
  NAND _1043_ (
    .A(balanceInicial[31]),
    .B(_0040_),
    .Y(_0427_)
  );
  NOR _1044_ (
    .A(balanceInicial[25]),
    .B(_0046_),
    .Y(_0428_)
  );
  NAND _1045_ (
    .A(_0015_),
    .B(monto[25]),
    .Y(_0429_)
  );
  NAND _1046_ (
    .A(balanceInicial[25]),
    .B(_0046_),
    .Y(_0430_)
  );
  NAND _1047_ (
    .A(_0429_),
    .B(_0430_),
    .Y(_0431_)
  );
  NAND _1048_ (
    .A(_0016_),
    .B(monto[24]),
    .Y(_0432_)
  );
  NAND _1049_ (
    .A(_0009_),
    .B(monto[31]),
    .Y(_0433_)
  );
  NOR _1050_ (
    .A(balanceInicial[26]),
    .B(_0045_),
    .Y(_0434_)
  );
  NAND _1051_ (
    .A(_0014_),
    .B(monto[26]),
    .Y(_0435_)
  );
  NOR _1052_ (
    .A(balanceInicial[27]),
    .B(_0044_),
    .Y(_0436_)
  );
  NOR _1053_ (
    .A(_0014_),
    .B(monto[26]),
    .Y(_0437_)
  );
  NOR _1054_ (
    .A(_0013_),
    .B(monto[27]),
    .Y(_0438_)
  );
  NOR _1055_ (
    .A(_0436_),
    .B(_0438_),
    .Y(_0439_)
  );
  NAND _1056_ (
    .A(_0435_),
    .B(_0439_),
    .Y(_0440_)
  );
  NOR _1057_ (
    .A(_0437_),
    .B(_0440_),
    .Y(_0441_)
  );
  NOR _1058_ (
    .A(balanceInicial[29]),
    .B(_0042_),
    .Y(_0442_)
  );
  NAND _1059_ (
    .A(_0011_),
    .B(monto[29]),
    .Y(_0443_)
  );
  NAND _1060_ (
    .A(balanceInicial[29]),
    .B(_0042_),
    .Y(_0444_)
  );
  NAND _1061_ (
    .A(_0443_),
    .B(_0444_),
    .Y(_0445_)
  );
  NAND _1062_ (
    .A(_0012_),
    .B(monto[28]),
    .Y(_0446_)
  );
  NAND _1063_ (
    .A(balanceInicial[28]),
    .B(_0043_),
    .Y(_0447_)
  );
  NAND _1064_ (
    .A(_0446_),
    .B(_0447_),
    .Y(_0448_)
  );
  NOR _1065_ (
    .A(_0445_),
    .B(_0448_),
    .Y(_0449_)
  );
  NAND _1066_ (
    .A(_0427_),
    .B(_0433_),
    .Y(_0450_)
  );
  NAND _1067_ (
    .A(_0425_),
    .B(_0426_),
    .Y(_0451_)
  );
  NOR _1068_ (
    .A(_0450_),
    .B(_0451_),
    .Y(_0452_)
  );
  NAND _1069_ (
    .A(_0449_),
    .B(_0452_),
    .Y(_0453_)
  );
  NAND _1070_ (
    .A(_0424_),
    .B(_0432_),
    .Y(_0454_)
  );
  NOR _1071_ (
    .A(_0431_),
    .B(_0454_),
    .Y(_0455_)
  );
  NAND _1072_ (
    .A(_0441_),
    .B(_0455_),
    .Y(_0456_)
  );
  NOR _1073_ (
    .A(_0453_),
    .B(_0456_),
    .Y(_0457_)
  );
  NOR _1074_ (
    .A(balanceInicial[23]),
    .B(_0048_),
    .Y(_0458_)
  );
  NOR _1075_ (
    .A(_0017_),
    .B(monto[23]),
    .Y(_0459_)
  );
  NOR _1076_ (
    .A(_0458_),
    .B(_0459_),
    .Y(_0460_)
  );
  NOR _1077_ (
    .A(_0018_),
    .B(monto[22]),
    .Y(_0461_)
  );
  NAND _1078_ (
    .A(_0022_),
    .B(monto[18]),
    .Y(_0462_)
  );
  NOR _1079_ (
    .A(balanceInicial[17]),
    .B(_0054_),
    .Y(_0463_)
  );
  NAND _1080_ (
    .A(_0023_),
    .B(monto[17]),
    .Y(_0464_)
  );
  NOR _1081_ (
    .A(_0023_),
    .B(monto[17]),
    .Y(_0465_)
  );
  NOR _1082_ (
    .A(_0463_),
    .B(_0465_),
    .Y(_0466_)
  );
  NOR _1083_ (
    .A(balanceInicial[16]),
    .B(_0055_),
    .Y(_0467_)
  );
  NOR _1084_ (
    .A(balanceInicial[22]),
    .B(_0049_),
    .Y(_0468_)
  );
  NAND _1085_ (
    .A(_0018_),
    .B(monto[22]),
    .Y(_0469_)
  );
  NOR _1086_ (
    .A(balanceInicial[21]),
    .B(_0050_),
    .Y(_0470_)
  );
  NAND _1087_ (
    .A(_0019_),
    .B(monto[21]),
    .Y(_0471_)
  );
  NOR _1088_ (
    .A(_0019_),
    .B(monto[21]),
    .Y(_0472_)
  );
  NOR _1089_ (
    .A(_0470_),
    .B(_0472_),
    .Y(_0473_)
  );
  NOR _1090_ (
    .A(balanceInicial[20]),
    .B(_0051_),
    .Y(_0474_)
  );
  NOR _1091_ (
    .A(_0020_),
    .B(monto[20]),
    .Y(_0475_)
  );
  NOR _1092_ (
    .A(_0474_),
    .B(_0475_),
    .Y(_0476_)
  );
  NAND _1093_ (
    .A(_0473_),
    .B(_0476_),
    .Y(_0477_)
  );
  NOT _1094_ (
    .A(_0477_),
    .Y(_0478_)
  );
  NOR _1095_ (
    .A(balanceInicial[19]),
    .B(_0052_),
    .Y(_0479_)
  );
  NOR _1096_ (
    .A(_0021_),
    .B(monto[19]),
    .Y(_0480_)
  );
  NOR _1097_ (
    .A(_0479_),
    .B(_0480_),
    .Y(_0481_)
  );
  NAND _1098_ (
    .A(balanceInicial[16]),
    .B(_0055_),
    .Y(_0482_)
  );
  NOR _1099_ (
    .A(_0022_),
    .B(monto[18]),
    .Y(_0483_)
  );
  NAND _1100_ (
    .A(balanceInicial[18]),
    .B(_0053_),
    .Y(_0484_)
  );
  NAND _1101_ (
    .A(_0460_),
    .B(_0469_),
    .Y(_0485_)
  );
  NOR _1102_ (
    .A(_0461_),
    .B(_0485_),
    .Y(_0486_)
  );
  NAND _1103_ (
    .A(_0478_),
    .B(_0486_),
    .Y(_0487_)
  );
  NAND _1104_ (
    .A(_0462_),
    .B(_0481_),
    .Y(_0488_)
  );
  NOR _1105_ (
    .A(_0483_),
    .B(_0488_),
    .Y(_0489_)
  );
  NAND _1106_ (
    .A(_0482_),
    .B(_0489_),
    .Y(_0490_)
  );
  NOR _1107_ (
    .A(_0487_),
    .B(_0490_),
    .Y(_0491_)
  );
  NAND _1108_ (
    .A(_0466_),
    .B(_0491_),
    .Y(_0492_)
  );
  NOR _1109_ (
    .A(_0467_),
    .B(_0492_),
    .Y(_0493_)
  );
  NAND _1110_ (
    .A(_0457_),
    .B(_0493_),
    .Y(_0494_)
  );
  NOR _1111_ (
    .A(_0423_),
    .B(_0494_),
    .Y(_0495_)
  );
  NAND _1112_ (
    .A(_0473_),
    .B(_0474_),
    .Y(_0496_)
  );
  NAND _1113_ (
    .A(_0471_),
    .B(_0496_),
    .Y(_0497_)
  );
  NAND _1114_ (
    .A(_0466_),
    .B(_0467_),
    .Y(_0498_)
  );
  NAND _1115_ (
    .A(_0464_),
    .B(_0498_),
    .Y(_0499_)
  );
  NAND _1116_ (
    .A(_0484_),
    .B(_0499_),
    .Y(_0500_)
  );
  NAND _1117_ (
    .A(_0462_),
    .B(_0500_),
    .Y(_0501_)
  );
  NOT _1118_ (
    .A(_0501_),
    .Y(_0502_)
  );
  NOR _1119_ (
    .A(_0480_),
    .B(_0502_),
    .Y(_0503_)
  );
  NOR _1120_ (
    .A(_0479_),
    .B(_0503_),
    .Y(_0504_)
  );
  NOR _1121_ (
    .A(_0477_),
    .B(_0504_),
    .Y(_0505_)
  );
  NOR _1122_ (
    .A(_0497_),
    .B(_0505_),
    .Y(_0506_)
  );
  NOR _1123_ (
    .A(_0461_),
    .B(_0506_),
    .Y(_0507_)
  );
  NOR _1124_ (
    .A(_0468_),
    .B(_0507_),
    .Y(_0508_)
  );
  NOR _1125_ (
    .A(_0459_),
    .B(_0508_),
    .Y(_0509_)
  );
  NOR _1126_ (
    .A(_0458_),
    .B(_0509_),
    .Y(_0510_)
  );
  NOT _1127_ (
    .A(_0510_),
    .Y(_0511_)
  );
  NAND _1128_ (
    .A(_0457_),
    .B(_0511_),
    .Y(_0512_)
  );
  NOR _1129_ (
    .A(_0445_),
    .B(_0446_),
    .Y(_0513_)
  );
  NOR _1130_ (
    .A(_0442_),
    .B(_0513_),
    .Y(_0514_)
  );
  NOR _1131_ (
    .A(_0431_),
    .B(_0432_),
    .Y(_0515_)
  );
  NOR _1132_ (
    .A(_0428_),
    .B(_0515_),
    .Y(_0516_)
  );
  NOR _1133_ (
    .A(_0437_),
    .B(_0516_),
    .Y(_0517_)
  );
  NOR _1134_ (
    .A(_0434_),
    .B(_0517_),
    .Y(_0518_)
  );
  NOR _1135_ (
    .A(_0438_),
    .B(_0518_),
    .Y(_0519_)
  );
  NOR _1136_ (
    .A(_0436_),
    .B(_0519_),
    .Y(_0520_)
  );
  NOT _1137_ (
    .A(_0520_),
    .Y(_0521_)
  );
  NAND _1138_ (
    .A(_0449_),
    .B(_0521_),
    .Y(_0522_)
  );
  NAND _1139_ (
    .A(_0514_),
    .B(_0522_),
    .Y(_0523_)
  );
  NAND _1140_ (
    .A(_0426_),
    .B(_0523_),
    .Y(_0524_)
  );
  NAND _1141_ (
    .A(_0425_),
    .B(_0524_),
    .Y(_0525_)
  );
  NAND _1142_ (
    .A(_0427_),
    .B(_0525_),
    .Y(_0526_)
  );
  NAND _1143_ (
    .A(_0433_),
    .B(_0526_),
    .Y(_0527_)
  );
  NOT _1144_ (
    .A(_0527_),
    .Y(_0528_)
  );
  NAND _1145_ (
    .A(_0512_),
    .B(_0528_),
    .Y(_0529_)
  );
  NOR _1146_ (
    .A(_0495_),
    .B(_0529_),
    .Y(_0530_)
  );
  NOR _1147_ (
    .A(balanceInicial[41]),
    .B(balanceInicial[40]),
    .Y(_0531_)
  );
  NOR _1148_ (
    .A(balanceInicial[39]),
    .B(balanceInicial[38]),
    .Y(_0532_)
  );
  NAND _1149_ (
    .A(_0531_),
    .B(_0532_),
    .Y(_0533_)
  );
  NOR _1150_ (
    .A(balanceInicial[43]),
    .B(balanceInicial[42]),
    .Y(_0534_)
  );
  NOR _1151_ (
    .A(balanceInicial[45]),
    .B(balanceInicial[44]),
    .Y(_0535_)
  );
  NAND _1152_ (
    .A(_0534_),
    .B(_0535_),
    .Y(_0536_)
  );
  NOR _1153_ (
    .A(_0533_),
    .B(_0536_),
    .Y(_0537_)
  );
  NOR _1154_ (
    .A(balanceInicial[33]),
    .B(balanceInicial[32]),
    .Y(_0538_)
  );
  NOR _1155_ (
    .A(balanceInicial[62]),
    .B(balanceInicial[63]),
    .Y(_0539_)
  );
  NAND _1156_ (
    .A(_0538_),
    .B(_0539_),
    .Y(_0540_)
  );
  NOR _1157_ (
    .A(balanceInicial[37]),
    .B(balanceInicial[36]),
    .Y(_0541_)
  );
  NOR _1158_ (
    .A(balanceInicial[35]),
    .B(balanceInicial[34]),
    .Y(_0542_)
  );
  NAND _1159_ (
    .A(_0541_),
    .B(_0542_),
    .Y(_0543_)
  );
  NOR _1160_ (
    .A(_0540_),
    .B(_0543_),
    .Y(_0544_)
  );
  NAND _1161_ (
    .A(_0537_),
    .B(_0544_),
    .Y(_0545_)
  );
  NOR _1162_ (
    .A(balanceInicial[57]),
    .B(balanceInicial[56]),
    .Y(_0546_)
  );
  NOR _1163_ (
    .A(balanceInicial[55]),
    .B(balanceInicial[54]),
    .Y(_0547_)
  );
  NAND _1164_ (
    .A(_0546_),
    .B(_0547_),
    .Y(_0548_)
  );
  NOR _1165_ (
    .A(balanceInicial[59]),
    .B(balanceInicial[58]),
    .Y(_0549_)
  );
  NOR _1166_ (
    .A(balanceInicial[61]),
    .B(balanceInicial[60]),
    .Y(_0550_)
  );
  NAND _1167_ (
    .A(_0549_),
    .B(_0550_),
    .Y(_0551_)
  );
  NOR _1168_ (
    .A(_0548_),
    .B(_0551_),
    .Y(_0552_)
  );
  NOR _1169_ (
    .A(balanceInicial[49]),
    .B(balanceInicial[48]),
    .Y(_0553_)
  );
  NOR _1170_ (
    .A(balanceInicial[47]),
    .B(balanceInicial[46]),
    .Y(_0554_)
  );
  NAND _1171_ (
    .A(_0553_),
    .B(_0554_),
    .Y(_0555_)
  );
  NOR _1172_ (
    .A(balanceInicial[53]),
    .B(balanceInicial[52]),
    .Y(_0556_)
  );
  NOR _1173_ (
    .A(balanceInicial[51]),
    .B(balanceInicial[50]),
    .Y(_0557_)
  );
  NAND _1174_ (
    .A(_0556_),
    .B(_0557_),
    .Y(_0558_)
  );
  NOR _1175_ (
    .A(_0555_),
    .B(_0558_),
    .Y(_0559_)
  );
  NAND _1176_ (
    .A(_0552_),
    .B(_0559_),
    .Y(_0560_)
  );
  NOR _1177_ (
    .A(_0545_),
    .B(_0560_),
    .Y(_0561_)
  );
  NOT _1178_ (
    .A(_0561_),
    .Y(_0562_)
  );
  NOR _1179_ (
    .A(_0530_),
    .B(_0562_),
    .Y(_0563_)
  );
  NOR _1180_ (
    .A(_0108_),
    .B(_0563_),
    .Y(_0564_)
  );
  NAND _1181_ (
    .A(state[1]),
    .B(_0564_),
    .Y(_0565_)
  );
  NOT _1182_ (
    .A(_0565_),
    .Y(entregarDinero)
  );
  NAND _1183_ (
    .A(state[2]),
    .B(montoSTB),
    .Y(_0566_)
  );
  NAND _1184_ (
    .A(_0565_),
    .B(_0566_),
    .Y(balanceActualizado)
  );
  NOR _1185_ (
    .A(_0121_),
    .B(_0191_),
    .Y(_0567_)
  );
  NAND _1186_ (
    .A(state[4]),
    .B(_0567_),
    .Y(_0568_)
  );
  NOR _1187_ (
    .A(_0095_),
    .B(_0568_),
    .Y(_0569_)
  );
  NOR _1188_ (
    .A(state[1]),
    .B(_0569_),
    .Y(_0570_)
  );
  NOR _1189_ (
    .A(_0096_),
    .B(_0570_),
    .Y(_0004_)
  );
  NOR _1190_ (
    .A(tipoTrans),
    .B(_0568_),
    .Y(_0571_)
  );
  NOR _1191_ (
    .A(state[2]),
    .B(_0571_),
    .Y(_0572_)
  );
  NOR _1192_ (
    .A(_0096_),
    .B(_0572_),
    .Y(_0005_)
  );
  NOR _1193_ (
    .A(cntPinIncorr[2]),
    .B(_0200_),
    .Y(_0573_)
  );
  NAND _1194_ (
    .A(_0089_),
    .B(_0199_),
    .Y(_0574_)
  );
  NOR _1195_ (
    .A(_0096_),
    .B(_0195_),
    .Y(_0575_)
  );
  NAND _1196_ (
    .A(_0573_),
    .B(_0575_),
    .Y(_0576_)
  );
  NAND _1197_ (
    .A(rst),
    .B(state[3]),
    .Y(_0577_)
  );
  NAND _1198_ (
    .A(_0576_),
    .B(_0577_),
    .Y(_0006_)
  );
  NAND _1199_ (
    .A(rst),
    .B(_0109_),
    .Y(_0578_)
  );
  NAND _1200_ (
    .A(_0574_),
    .B(_0575_),
    .Y(_0579_)
  );
  NAND _1201_ (
    .A(_0578_),
    .B(_0579_),
    .Y(_0007_)
  );
  NAND _1202_ (
    .A(state[4]),
    .B(_0121_),
    .Y(_0580_)
  );
  NOT _1203_ (
    .A(_0580_),
    .Y(_0581_)
  );
  NAND _1204_ (
    .A(tarjetaRecibida),
    .B(state[0]),
    .Y(_0582_)
  );
  NAND _1205_ (
    .A(_0228_),
    .B(_0582_),
    .Y(_0583_)
  );
  NOR _1206_ (
    .A(_0581_),
    .B(_0583_),
    .Y(_0584_)
  );
  NOR _1207_ (
    .A(_0096_),
    .B(_0584_),
    .Y(_0008_)
  );
  NAND _1208_ (
    .A(_0098_),
    .B(state[0]),
    .Y(_0585_)
  );
  NAND _1209_ (
    .A(rst),
    .B(_0585_),
    .Y(_0003_)
  );
  NAND _1210_ (
    .A(_0089_),
    .B(_0198_),
    .Y(_0586_)
  );
  NOR _1211_ (
    .A(_0195_),
    .B(_0586_),
    .Y(advertencia)
  );
  NOR _1212_ (
    .A(_0093_),
    .B(_0564_),
    .Y(fondosInsuficientes)
  );
  NAND _1213_ (
    .A(pinIngresado[11]),
    .B(_0109_),
    .Y(_0587_)
  );
  NAND _1214_ (
    .A(pinIngresado[15]),
    .B(_0230_),
    .Y(_0588_)
  );
  NAND _1215_ (
    .A(_0587_),
    .B(_0588_),
    .Y(_0589_)
  );
  NAND _1216_ (
    .A(rst),
    .B(_0589_),
    .Y(_0590_)
  );
  NOT _1217_ (
    .A(_0590_),
    .Y(_0002_[15])
  );
  NAND _1218_ (
    .A(cntPinIncorr[1]),
    .B(cntPinIncorr[0]),
    .Y(_0591_)
  );
  NOR _1219_ (
    .A(_0195_),
    .B(_0591_),
    .Y(_0592_)
  );
  NAND _1220_ (
    .A(cntPinIncorr[2]),
    .B(_0592_),
    .Y(_0593_)
  );
  NOR _1221_ (
    .A(cntPinIncorr[2]),
    .B(_0592_),
    .Y(_0594_)
  );
  NAND _1222_ (
    .A(rst),
    .B(_0593_),
    .Y(_0595_)
  );
  NOR _1223_ (
    .A(_0594_),
    .B(_0595_),
    .Y(_0001_[2])
  );
  NAND _1224_ (
    .A(cntDigito[1]),
    .B(cntDigito[0]),
    .Y(_0596_)
  );
  NOR _1225_ (
    .A(_0097_),
    .B(_0596_),
    .Y(_0597_)
  );
  NAND _1226_ (
    .A(cntDigito[2]),
    .B(_0597_),
    .Y(_0598_)
  );
  NAND _1227_ (
    .A(state[5]),
    .B(_0598_),
    .Y(_0599_)
  );
  NAND _1228_ (
    .A(_0580_),
    .B(_0599_),
    .Y(_0600_)
  );
  NOR _1229_ (
    .A(_0208_),
    .B(_0600_),
    .Y(_0601_)
  );
  NAND _1230_ (
    .A(state[5]),
    .B(_0597_),
    .Y(_0602_)
  );
  NAND _1231_ (
    .A(_0086_),
    .B(_0602_),
    .Y(_0603_)
  );
  NAND _1232_ (
    .A(rst),
    .B(_0603_),
    .Y(_0604_)
  );
  NOR _1233_ (
    .A(_0601_),
    .B(_0604_),
    .Y(_0000_[2])
  );
  BUF _1234_ (
    .A(state[3]),
    .Y(alarmaBloqueo)
  );
  (* src = "atm.v:37.1-52.4" *)
  DFF _1235_ (
    .C(clk),
    .D(_0000_[0]),
    .Q(cntDigito[0])
  );
  (* src = "atm.v:37.1-52.4" *)
  DFF _1236_ (
    .C(clk),
    .D(_0000_[1]),
    .Q(cntDigito[1])
  );
  (* src = "atm.v:37.1-52.4" *)
  DFF _1237_ (
    .C(clk),
    .D(_0000_[2]),
    .Q(cntDigito[2])
  );
  (* src = "atm.v:37.1-52.4" *)
  DFF _1238_ (
    .C(clk),
    .D(_0001_[0]),
    .Q(cntPinIncorr[0])
  );
  (* src = "atm.v:37.1-52.4" *)
  DFF _1239_ (
    .C(clk),
    .D(_0001_[1]),
    .Q(cntPinIncorr[1])
  );
  (* src = "atm.v:37.1-52.4" *)
  DFF _1240_ (
    .C(clk),
    .D(_0001_[2]),
    .Q(cntPinIncorr[2])
  );
  (* src = "atm.v:37.1-52.4" *)
  DFF _1241_ (
    .C(clk),
    .D(_0002_[0]),
    .Q(pinIngresado[0])
  );
  (* src = "atm.v:37.1-52.4" *)
  DFF _1242_ (
    .C(clk),
    .D(_0002_[1]),
    .Q(pinIngresado[1])
  );
  (* src = "atm.v:37.1-52.4" *)
  DFF _1243_ (
    .C(clk),
    .D(_0002_[2]),
    .Q(pinIngresado[2])
  );
  (* src = "atm.v:37.1-52.4" *)
  DFF _1244_ (
    .C(clk),
    .D(_0002_[3]),
    .Q(pinIngresado[3])
  );
  (* src = "atm.v:37.1-52.4" *)
  DFF _1245_ (
    .C(clk),
    .D(_0002_[4]),
    .Q(pinIngresado[4])
  );
  (* src = "atm.v:37.1-52.4" *)
  DFF _1246_ (
    .C(clk),
    .D(_0002_[5]),
    .Q(pinIngresado[5])
  );
  (* src = "atm.v:37.1-52.4" *)
  DFF _1247_ (
    .C(clk),
    .D(_0002_[6]),
    .Q(pinIngresado[6])
  );
  (* src = "atm.v:37.1-52.4" *)
  DFF _1248_ (
    .C(clk),
    .D(_0002_[7]),
    .Q(pinIngresado[7])
  );
  (* src = "atm.v:37.1-52.4" *)
  DFF _1249_ (
    .C(clk),
    .D(_0002_[8]),
    .Q(pinIngresado[8])
  );
  (* src = "atm.v:37.1-52.4" *)
  DFF _1250_ (
    .C(clk),
    .D(_0002_[9]),
    .Q(pinIngresado[9])
  );
  (* src = "atm.v:37.1-52.4" *)
  DFF _1251_ (
    .C(clk),
    .D(_0002_[10]),
    .Q(pinIngresado[10])
  );
  (* src = "atm.v:37.1-52.4" *)
  DFF _1252_ (
    .C(clk),
    .D(_0002_[11]),
    .Q(pinIngresado[11])
  );
  (* src = "atm.v:37.1-52.4" *)
  DFF _1253_ (
    .C(clk),
    .D(_0002_[12]),
    .Q(pinIngresado[12])
  );
  (* src = "atm.v:37.1-52.4" *)
  DFF _1254_ (
    .C(clk),
    .D(_0002_[13]),
    .Q(pinIngresado[13])
  );
  (* src = "atm.v:37.1-52.4" *)
  DFF _1255_ (
    .C(clk),
    .D(_0002_[14]),
    .Q(pinIngresado[14])
  );
  (* src = "atm.v:37.1-52.4" *)
  DFF _1256_ (
    .C(clk),
    .D(_0002_[15]),
    .Q(pinIngresado[15])
  );
  DFF _1257_ (
    .C(clk),
    .D(_0003_),
    .Q(state[0])
  );
  DFF _1258_ (
    .C(clk),
    .D(_0004_),
    .Q(state[1])
  );
  DFF _1259_ (
    .C(clk),
    .D(_0005_),
    .Q(state[2])
  );
  DFF _1260_ (
    .C(clk),
    .D(_0006_),
    .Q(state[3])
  );
  DFF _1261_ (
    .C(clk),
    .D(_0007_),
    .Q(state[4])
  );
  DFF _1262_ (
    .C(clk),
    .D(_0008_),
    .Q(state[5])
  );
endmodule
